import React from 'react'

export default

<div>
  <h1>Orientations Communes </h1>
  <br/>
  <h2 className="center-title">Un autre PAACte entre les paysan·ne·s et la société </h2>
  <br/>
  <p>&emsp;&emsp;&emsp;La Politique Agricole Commune (PAC) 2014-2020 a manqué sa cible. Elle était annoncée comme plus verte et plus juste, mais elle n’a en réalité pas changé de cap ni arrêté le rouleau compresseur auquel la nature et les agriculteur·rice·s sont soumis. En effet, la PAC 2014-2020 s’est illustrée par le manque total d’ambition du verdissement, la discrimination des critères envers les petites fermes, l’absence de plafonnement, la persistance du déséquilibre entre 1er et 2ème piliers et le parachèvement de la dérégulation. De surcroît, en France, la confiance des agriculteur·rice·s en cette politique a été profondément ébranlée par son incohérence, sa complexité, son incapacité à leur permettre de tirer un revenu de leur production, et surtout, par l’instabilité des dispositifs.
  </p>
  <br/>
  <p>&emsp;&emsp;&emsp;Face à ce constat, la réforme de cette politique apparait comme l’opportunité majeure pour toute une génération de réinsuffler des perspectives d’avenir pour le secteur agricole français, tout en répondant aux multiples attentes sociétales en matière d’alimentation, d’emploi, de bien-être animal, d’environnement, de santé, de respect des paysans des pays en développement, ainsi que de luttes contre les changements climatiques, contre l’artificialisation et l’accaparement des terres.
  </p>
  <br/>
  <p>&emsp;&emsp;&emsp;Réunissant trente organisations paysannes, environnementales, de solidarité internationale et de citoyen·ne·s-consommateur·rice·s, la plateforme  <i>Pour une autre PAC</i> demande aux décideur·se·s politiques de porter avec ambition et courage une révision complète de la PAC pour la transformer en un nouveau PAACte (pacte fondé sur une nouvelle politique agricole et alimentaire commune) entre les paysan·ne·s et la société, permettant tout à la fois aux premier·ère·s de vivre fièrement de leur métier et à leurs concitoyen·ne·s de profiter des bienfaits de leur activité.
  </p>
  <br/>
  <h2>Mettre la future Politique Agricole et Alimentaire Commune au service de tous les citoyen·ne·s</h2>
  <p>Une politique agricole et alimentaire constitue bien plus qu’un budget sectoriel : c’est un véritable enjeu de société. Il est urgent de créer un pacte entre paysan·ne·s et citoyen·ne·s européen·ne·s, qui impulse à grande échelle la nécessaire mutation du système agro-industriel et qui scelle leur détermination conjointe à développer un modèle alimentaire durable. De là dépend la pérennité des moyens de production de l’agriculture de l’UE, au premier rang desquels figurent les paysan·ne·s et par conséquent, leur rémunération par des prix justes et stables au sein de filières équitables. Une PAAC pour tous s’adresse donc aussi aux agriculteur·rice·s dont le modèle de production ne correspond plus ni à la réalité d’un marché mondial libéralisé, ni aux attentes des citoyen·ne·s, par le biais de contrats de transition aux conditions et échéances clairement définis.</p>
  <br/>
  <h2>Atteindre la souveraineté, l’autonomie et la qualité alimentaires dans l’UE</h2>
  <p>La PAAC doit être une politique agricole nourricière, sans incitation à une augmentation systématique des volumes de production, mais en reliant ces derniers à la demande européenne concernant d’une part, des denrées de qualité sur le plan sanitaire, en particulier exemptes de pesticides, et d’autre part, des régimes alimentaires équilibrés, notamment moins riches en protéines animales. La recherche d’une souveraineté alimentaire européenne suppose de réduire la dépendance aux productions extra-communautaires pour en favoriser unerelocalisée et diversifiée, respectueuse de la spécificité des territoires de l’UE, au bénéfice conjoint des paysan·ne·s et des consommateur·rices·s européen·ne·s.</p>
  <br/>
  <h2>Mettre en cohérence la PAAC avec les politiques de développement des agricultures familiales et paysannes des pays du Sud</h2>
  <p>Inscrite dans les traités de l’UE et la loi française, la cohérence des politiques pour le développement impose à la nouvelle PAAC de contribuer à la réalisation des Objectifs de développement durable (ODD) des Nations unies. C’est pourquoi la réforme de la PAAC invite à réaffirmer le principe de solidarité entre tous les paysan·ne·s et à reconnaitre les enjeux particuliers de l’échange des produits agricoles bruts et transformés dans les règles commerciales mondiales. Pour cela, l’UE doit renoncer aux accords de libre-échange non compatibles avec le commerce équitable, mettre un terme aux exportations subventionnées, ainsi que limiter les importations causant des dommages à la fois aux systèmes agricoles et alimentaires des pays de Sud et à leur environnement.</p>
  <br/>
  <h2>Enclencher une transition agroécologique grâce à la réorientation des paiements</h2>
  <p>Les paiements de la PAAC constituent un levier financier fondamental pour guider les filières agro-alimentaires vers une transition agroécologique. Pour ce faire, leurs critères d’allocation doivent se baser sur deux outils : une conditionnalité liée à des normes réglementaires et la rémunération des services rendus à la société. D’une part, la PAAC se fonde sur une triple conditionnalité environnementale (protection de l’eau, de l’air, de la biodiversité, des sols et du bien-être animal), sociale (droit du travail pour les salarié·e·s agricoles) et économique (modulation et plafonnement des aides par actif). D’autre part, elle passe d’une logique de palliation des effets négatifs de l’agriculture productiviste à celle de valorisation des externalités positives, via une rétribution proportionnelle aux engagements des agriculteur·rice·s en faveur de pratiques vertueuses. Ainsi, la transition agroécologique doit être soutenue sans distorsion entre les territoires ni exemptions entre les paysan·ne·s, en tenant compte des efforts fournis et non de références agricoles caduques.</p>
  <br/>
  <h2>Accompagner la résilience technique et économique des fermes en inversant la logique des mécanismes de la PAC</h2>
  <p>Dans un contexte d’instabilité permanente, la réforme de la PAAC doit permettre aux agriculteur.rice.s d’améliorer leur résilience technique et économique face aux aléas climatiques ou sanitaires, en encourageant leur autonomie dans le pilotage de leur activité, la réduction des coûts de production et la diversification, dont celle de la biodiversité cultivée. À cet égard, le financement public des systèmes assurantiels privés n’apporte aucune solution durable : il entretient seulement l’image d’un·e. exploitant·e impuissant·e face à des fléaux inéluctables, alors qu’il ou elle fait en fait le choix de ne pas anticiper. Au contraire, la réallocation des aides les guide vers la sortie du cercle vicieux du « produire toujours plus pour toujours moins » dessiné par l’agro-industrie. De même, le nouvelle PAAC doit permettre à l’UE de minimiser les perturbations de marché, grâce à la réaffirmation de la préférence communautaire et à la révision du droit européen de la concurrence.</p>
  <br/>
  <h2>Relancer l’emploi dans les campagnes par la politique de développement rural</h2>
  <p>Pour faire face à l’urgence de renouvellement et de démultiplication des actifs agricoles, une PAAC cohérente intègre nécessairement la lutte contre la fragilisation, voire la disparition, des paysan·ne·s dans les campagnes et la revalorisation de leur métier. C’est pourquoi l’UE a besoin d’une politique foncière et d’aide à l’installation qui lutte contre la concentration et l’accaparement des terres et facilite l’installation de personnes non issues du milieu agricole, la transmission des fermes, ainsi que l’accès au foncier des petit·e·s agriculteur·rice·s, tout en les accompagnant dans le développement de projets créateurs de valeur ajoutée. De plus, la relance de l’emploi rural sur tous les territoires suppose de soutenir spécifiquement ceux caractérisés par des handicaps naturels ou structurels, assurant de surcroît le maintien de paysages variés et riches en biodiversité.</p>
  <br/>
  <h2>Repenser la gouvernance de la PAAC dans sa conception et son application</h2>
  <p>La future PAAC doit affirmer sa plus-value européenne, par opposition à une renationalisation des politiques agricoles, qui viderait de sa substance l’ambition des objectifs fixés par l’UE. Le niveau européen est garant de la solidarité financière entre citoyen·ne·s et agriculteur·rice·s des différents États membres.Par ailleurs, la définition de la future PAAC appelle à un processus démocratique délibératif à toutes les échelles de prise de décision et de mise en œuvre, au sein duquel, d’une part, les citoyen·ne·s sont réellement associé·e·s et d’autre part, les instances de gouvernance impliquées sont élargies à celles chargées de l’alimentation, des territoires, de la santé et de l’environnement. Enfin, une obligation d’évaluation indépendante et décisive des dispositifs doit être instaurée, afin de restaurer la légitimité et la lisibilité de la PAAC auprès de ses bénéficiaires.</p>
  <br/>
  <p>Orientations communes de la plateforme <i>Pour une autre PAC à télécharger</i></p>
</div>
